### ISSUE TITLE
Prática Python- Juliana de Carvalho e Clara Azar

### ISSUE THREAD

**Issue by Ju-Carvalho** [leouieda/mat-esp-python-intro-2015#1]
https://github.com/felipesurf/mat-esp-python-intro-2015

**Comment by leouieda** [comment]
@Ju-Carvalho e @clarazar, mais atenção as instruções do e-mail:

> Criem uma Issue em https://github.com/leouieda/matematica-especial com as informações
> 1. "Prática Python - Aluno 1, Aluno 2, Aluno 3" no título.
> 2. Qual turma vocês pertecem.
> 3. Nomes completos de todos os integrantes do grupo.
